version: '3.5'

services:

  postfix:
    image: tvial/docker-mailserver:latest
    hostname: smtp.kujon.mobi
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - /home/postfix/mail:/var/mail
    - /home/postfix/mail-state:/var/mail-state
    - /home/postfix/config/:/tmp/docker-mailserver/
    - ./nginx/ssl:/tmp/ssl:ro
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/kujon.mobi.cert.2018
    - SSL_KEY_PATH=/tmp/ssl/kujon.mobi.key
    deploy:
        placement:
          constraints: [node.hostname == d1.kujon.mobi]
    logging:
      driver: "syslog"

  nginx:
    image: r.kujon.mobi/nginx:0.1
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "syslog"
    depends_on:
      - app-demo
      - app-prod
    deploy:
        placement:
          constraints: [node.hostname == d1.kujon.mobi]

  app-demo:
    image: r.kujon.mobi/app-demo:0.21
    logging:
      driver: "syslog"
    depends_on:
      - mongodb
    deploy:
        placement:
          constraints: [node.hostname == d1.kujon.mobi]

  app-prod:
    image: r.kujon.mobi/app-prod:0.21
    logging:
      driver: "syslog"
    depends_on:
      - mongodb
    deploy:
        placement:
          constraints: [node.hostname == d1.kujon.mobi]

  mongodb:
    image: mongo:3.6
    volumes:
      - /home/mongodb/db:/data/db
      - /home/mongodb/configdb:/data/configdb
    environment:
      - AUTH=yes
    logging:
      driver: "syslog"
    deploy:
        replicas: 1
        placement:
          constraints: [node.hostname == d2.kujon.mobi]
