version: '3.5'

services:

  nginx:
    image: kujon/kujon-nginx
    ports:
      - "80:80"
      - "443:443"

  app:
    image: kujon/kujon-demo
    ports:
      - "9000:9000"
      - "9002:9002"
      - "9004:9004"
      - "9005:9005"
    networks:
      - frontend
      - backend


  mongodb:
    image: mongo:3.6
    volumes:
      - "mongodb:/var/lib/mongodb"
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=demo
      - MONGODB_APPLICATION_USER=kujon
      - MONGODB_APPLICATION_PASS=ZZ2982skhH3sGIms

networks:
  frontend:
  backend:

volumes:
  mongodb:

#  drupal:
#    ports:
#      - "80:80"
#    volumes:
#      - drupal-modules:/var/www/html/modules
#      - drupal-profiles:/var/www/html/profiles
#      - drupal-sites:/var/www/html/sites
#      - drupal-themes:/var/www/html/themes
#
#  postgres:
#    environment:
#      - POSTGRES_PASSWORD_FILE=/run/secrets/psql-pw
#    secrets:
#      - psql-pw
#    volumes:
#      - drupal-data:/var/lib/postgresql/data
#
#volumes:
#  drupal-data:
#  drupal-modules:
#  drupal-profiles:
#  drupal-sites:
#  drupal-themes:
#
#secrets:
#  psql-pw:
#    external: true
