version: '3.5'

services:

  mail:
    image: tvial/docker-mailserver:latest
    hostname: smtp.kujon.mobi
    domainname: kujon.mobi
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - /home/postfix/config/:/tmp/docker-mailserver/
    - ./nginx/ssl:/tmp/ssl:ro
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/kujon.mobi.cert.2018
    - SSL_KEY_PATH=/tmp/ssl/kujon.mobi.key
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    deploy:
        replicas: 1
        placement:
          constraints: [node.hostname == d1.kujon.mobi]
    restart: always
    
  nginx:
    image: r.kujon.mobi/nginx:0.1
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "20"
    depends_on:
      - demo
      - prod

  demo:
    image: r.kujon.mobi/app:0.1
    environment:
      - CONFIG=demo
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/usosesall"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 10s

  prod:
    image: r.kujon.mobi/app:0.1
    environment:
      - CONFIG=prod
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "40"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/usosesall"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:3.6
    volumes:
      - /home/mongodb/db:/data/db
      - /home/mongodb/configdb:/data/configdb
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - AUTH=yes
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    deploy:
        replicas: 1
        placement:
          constraints: [node.hostname == d2.kujon.mobi]

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
