version: '3.5'

services:

  nginx:
    image: kujon/nginx-0.1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "20"

  demo:
    image: kujon/app-0.1
    ports:
      - "8000:8000"
      - "8002:8002"
      - "8004:8004"
      - "8005:8005"
    environment:
      - CONFIG=demo
    networks:
      - frontend
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  prod:
    image: kujon/app-0.1
    ports:
      - "8000:8000"
      - "8002:8002"
      - "8004:8004"
      - "8005:8005"
    environment:
      - CONFIG=prod
    networks:
      - frontend
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "40"

  mongodb:
    image: mongo:3.6
    volumes:
      - "mongodb:/var/lib/mongodb"
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      - AUTH=yes
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

networks:
  frontend:
  backend:

volumes:
  mongodb:
