version: '3.5'

services:

  nginx:
    image: r.kujon.mobi/nginx:0.1
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "20"
    depends_on:
      - demo
      - prod

  demo:
    image: r.kujon.mobi/app:0.1
    environment:
      - CONFIG=demo
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/usosesall"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 30s

  prod:
    image: r.kujon.mobi/app:0.1
    environment:
      - CONFIG=prod
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "40"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/usosesall"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 30s

  mongodb:
    image: mongo:3.6
    volumes:
      - /home/mongodb/db:/data/db
      - /home/mongodb/configdb:/data/configdb
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - AUTH=yes
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    deploy:
        replicas: 1
        placement:
          constraints: [node.hostname == d2.kujon.mobi]
