version: '3.5'

services:

  nginx:
    image: kujonmobi/server:kujon-nginx
    ports:
      - "80:80"
      - "443:443"

  app:
    image: kujonmobi/server:kujon-demo
    ports:
      - "9000:9000"
      - "9002:9002"
      - "9004:9004"
      - "9005:9005"
    networks:
      - frontend
      - backend


  mongodb:
    image: mongo:3.6
    volumes:
      - "mongodb:/var/lib/mongodb"
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=demo
      - MONGODB_APPLICATION_USER=kujon
      - MONGODB_APPLICATION_PASS=ZZ2982skhH3sGIms

networks:
  frontend:
  backend:

volumes:
  mongodb:
