version: '3.5'

services:

  nginx:
    image: r.kujon.mobi/nginx:0.1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "20"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - demo
      - prod

  demo:
    image: r.kujon.mobi/app:0.1
    ports:
      - "9000:8000"
      - "9002:8002"
      - "9004:8004"
      - "9005:8005"
    environment:
      - CONFIG=demo
    networks:
      - frontend
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/usosesall"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 30s

  prod:
    image: r.kujon.mobi/app:0.1
    ports:
      - "8000:8000"
      - "8002:8002"
      - "8004:8004"
      - "8005:8005"
    environment:
      - CONFIG=prod
    networks:
      - frontend
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "40"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/usosesall"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 30s

  mongodb:
    image: mongo:3.6
    volumes:
      - "mongodb:/var/lib/mongodb"
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      - AUTH=yes
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

networks:
  frontend:
  backend:

volumes:
  mongodb:
