version: '3.5'

services:

  postfix:
    image: tvial/docker-mailserver:latest
    hostname: smtp.kujon.mobi
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - /home/postfix/mail:/var/mail
    - /home/postfix/mail-state:/var/mail-state
    - /home/postfix/config/:/tmp/docker-mailserver/
    - ./nginx/ssl:/tmp/ssl:ro
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/kujon.mobi.cert.2018
    - SSL_KEY_PATH=/tmp/ssl/kujon.mobi.key
    deploy:
        replicas: 1
        placement:
          constraints: [node.hostname == d1.kujon.mobi]
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://r.kujon.mobi:514"

  nginx:
    image: r.kujon.mobi/nginx:0.1
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://r.kujon.mobi:514"
    depends_on:
      - app-development
      - app-master

  app-development:
    image: r.kujon.mobi/app-development:0.1
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://r.kujon.mobi:514"
    depends_on:
      - mongodb
      - postfix
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/usosesall"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 10s

  app-master:
    image: r.kujon.mobi/app-master:0.1
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://r.kujon.mobi:514"
    depends_on:
      - mongodb
      - postfix
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/usosesall"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:3.6
    volumes:
      - /home/mongodb/db:/data/db
      - /home/mongodb/configdb:/data/configdb
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - AUTH=yes
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://r.kujon.mobi:514"
    deploy:
        replicas: 1
        placement:
          constraints: [node.hostname == d2.kujon.mobi]
