version: '3.5'

services:

  nginx:
    image: kujon/nginx-0.1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

  demo:
    image: kujon/app-0.1
    ports:
      - "9000:8000"
      - "9002:8002"
      - "9004:8004"
      - "9005:8005"
    environment:
      - CONFIG=demo
    networks:
      - frontend
      - backend

  prod:
    image: kujon/app-0.1
    ports:
      - "8000:8000"
      - "8002:8002"
      - "8004:8004"
      - "8005:8005"
    environment:
      - CONFIG=prod
    networks:
      - frontend
      - backend


  mongodb:
    image: mongo:3.6
    volumes:
      - "mongodb:/var/lib/mongodb"
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=demo
      - MONGODB_APPLICATION_USER=kujon
      - MONGODB_APPLICATION_PASS=ZZ2982skhH3sGIms

networks:
  frontend:
  backend:

volumes:
  mongodb:
